import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';
import apiSidebar from './docs/api/sidebar';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // Main docs sidebar - manually exclude API folder
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Getting Started',
      items: [{type: 'autogenerated', dirName: 'getting-started'}],
    },
    {
      type: 'category',
      label: 'Core Concepts',
      items: [{type: 'autogenerated', dirName: 'core-concepts'}],
    },
    {
      type: 'category',
      label: 'Event Management',
      items: [{type: 'autogenerated', dirName: 'event-management'}],
    },
    {
      type: 'category',
      label: 'Attendee Management',
      items: [{type: 'autogenerated', dirName: 'attendee-management'}],
    },
    {
      type: 'category',
      label: 'Sessions & Speakers',
      items: [{type: 'autogenerated', dirName: 'sessions-speakers'}],
    },
    {
      type: 'category',
      label: 'Networking Features',
      items: [{type: 'autogenerated', dirName: 'networking-features'}],
    },
    {
      type: 'category',
      label: 'Chat & Messaging',
      items: [{type: 'autogenerated', dirName: 'chat-messaging'}],
    },
    {
      type: 'category',
      label: 'Sponsors',
      items: [{type: 'autogenerated', dirName: 'sponsors'}],
    },
    {
      type: 'category',
      label: 'Your Account',
      items: [{type: 'autogenerated', dirName: 'your-account'}],
    },
  ],

  // API docs sidebar (auto-generated from OpenAPI spec) - separate
  apisidebar: apiSidebar,

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
